apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: amazon-cloudwatch
  labels:
    app: cloudwatch-agent
data:
  cloudwatch-agent-config.json: |
    {
      "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "root"
      },
      "logs": {
        "logs_collected": {
          "kubernetes": {
            "cluster_name": "cluster-name",
            "logs_collected": {
              "namespaces": [
                "default"
              ],
              "log_stream_name": "logs-namespace"
            }
          }
        },
        "log_stream_name": "logs-node"
      },
      "metrics": {
        "metrics_collected": {
          "cpu": {
            "measurement": [
              "cpu_usage_idle",
              "cpu_usage_iowait"
            ],
            "metrics_collection_interval": 60,
            "resources": [
              "*"
            ]
          },
          "disk": {
            "measurement": [
              "disk_free",
              "disk_used"
            ],
            "metrics_collection_interval": 60,
            "resources": [
              "*"
            ]
          },
          "mem": {
            "measurement": [
              "mem_used_percent"
            ],
            "metrics_collection_interval": 60
          }
        }
      }
    }
