name: IAC

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  iac-workflow:
    uses: enescingil/common-iac/.github/workflows/k8-deployment.yml@main
    secrets: inherit
    with:
      service_account: gpc-tfiac-sa
      aws_region: us-east-2
      k8s_namespace: nginx-deployment